"""insert your copyright here.

# see the URL below for information on how to write OpenStudio measures
# http://nrel.github.io/OpenStudio-user-documentation/reference/measure_writing_guide/
"""

import typing
import openstudio
import pandas as pd
import numpy as np
import os

class ModifyStochasticFilePython(openstudio.measure.ModelMeasure):
    """A ModelMeasure."""

    def name(self):
        """Returns the human readable name.

        Measure name should be the title case of the class name.
        The measure name is the first contact a user has with the measure;
        it is also shared throughout the measure workflow, visible in the OpenStudio Application,
        PAT, Server Management Consoles, and in output reports.
        As such, measure names should clearly describe the measure's function,
        while remaining general in nature
        """
        return "Modify stochastic file using a python measure."

    def description(self):
        """Human readable description.

        The measure description is intended for a general audience and should not assume
        that the reader is familiar with the design and construction practices suggested by the measure.
        """
        return "This measure aims at modifying the stochastic csv file generated by the measure BuildResidentialScheduleFile from OpenStudio-HPXML workflow. The idea is to consider new stochastic profiles generated from models more representative of other regions. "

    def modeler_description(self):
        """Human readable description of modeling approach.

        The modeler description is intended for the energy modeler using the measure.
        It should explain the measure's intent, and include any requirements about
        how the baseline model must be set up, major assumptions made by the measure,
        and relevant citations or references to applicable modeling resources
        """
        return "Idem description"

    def arguments(self, model: typing.Optional[openstudio.model.Model] = None):
        """Prepares user arguments for the measure.

        Measure arguments define which -- if any -- input parameters the user may set before running the measure.
        """
        args = openstudio.measure.OSArgumentVector()

        csv_path = openstudio.measure.OSArgument.makeStringArgument("csv_path", True)
        csv_path.setDisplayName("Path to the CSV file.")
        csv_path.setDescription("Path to the stochastic CSV file that will be modified by this measure.")
        csv_path.setDefaultValue("stochastic.csv")

        args.append(csv_path)

        return args

    def run(
        self,
        model: openstudio.model.Model,
        runner: openstudio.measure.OSRunner,
        user_arguments: openstudio.measure.OSArgumentMap,
    ):
        """Defines what happens when the measure is run."""
        super().run(model, runner, user_arguments)  # Do **NOT** remove this line

        if not (runner.validateUserArguments(self.arguments(model), user_arguments)):
            return False

        csv_path = runner.getStringArgumentValue("csv_path", user_arguments)

        # check if the file exists
        if not os.path.exists(csv_path):
            runner.registerError(f"CSV file '{csv_path}' does not exist.")
            return False

        # read the CSV file with pandas
        # Using pandas to read the CSV file allows for easier manipulation and analysis of the data.
        try:
            df = pd.read_csv(csv_path)
        except Exception as e:
            runner.registerError(f"Failed to read CSV file '{csv_path}': {e}")
            return False
        
        # perform some modification to the dataframe
        df['plug_loads_vehicle'] = np.random.uniform(0, 1, size=df.shape[0])
        
        # write the modified dataframe back to the CSV file
        try:
            df.to_csv(csv_path, index=False)
        except Exception as e:
            runner.registerError(f"Failed to write CSV file '{csv_path}': {e}")
            return False

        # report success
        runner.registerInfo(f"Successfully modified the stochastic file at '{csv_path}'.")

        return True

# register the measure to be used by the application
ModifyStochasticFilePython().registerWithApplication()
