# -*- coding: utf-8 -*-
"""Stable column contract for the sampler export.

GENERATED FILE -- do not edit by hand. Regenerate with::

    python -m src.utils.hpxml.gen_hpxml_column_list

Observed over 8000 buildings (5 batches of 800 per network).
"""

HPXML_COLUMNS = [
    "simulation_control_daylight_saving_enabled",
    "simulation_control_ground_to_air_heat_pump_model_type",
    "site_shielding_of_home",
    "site_time_zone_utc_offset",
    "weather_station_epw_filepath",
    "year_built",
    "geometry_unit_type",
    "geometry_unit_left_wall_is_adiabatic",
    "geometry_unit_right_wall_is_adiabatic",
    "geometry_unit_front_wall_is_adiabatic",
    "geometry_unit_back_wall_is_adiabatic",
    "geometry_unit_num_floors_above_grade",
    "geometry_unit_cfa",
    "geometry_unit_aspect_ratio",
    "geometry_unit_orientation",
    "geometry_unit_num_bedrooms",
    "geometry_unit_num_occupants",
    "geometry_building_num_units",
    "geometry_average_ceiling_height",
    "geometry_garage_width",
    "geometry_garage_depth",
    "geometry_garage_protrusion",
    "geometry_garage_position",
    "geometry_foundation_type",
    "geometry_foundation_height",
    "geometry_foundation_height_above_grade",
    "geometry_rim_joist_height",
    "geometry_attic_type",
    "geometry_roof_type",
    "geometry_roof_pitch",
    "floor_over_foundation_assembly_r",
    "floor_over_garage_assembly_r",
    "floor_type",
    "foundation_wall_type",
    "foundation_wall_insulation_r",
    "foundation_wall_insulation_location",
    "foundation_wall_insulation_distance_to_top",
    "rim_joist_assembly_r",
    "slab_perimeter_insulation_r",
    "slab_perimeter_insulation_depth",
    "slab_under_insulation_r",
    "slab_under_insulation_width",
    "ceiling_assembly_r",
    "roof_material_type",
    "roof_color",
    "roof_assembly_r",
    "radiant_barrier_attic_location",
    "radiant_barrier_grade",
    "wall_type",
    "wall_siding_type",
    "wall_color",
    "wall_assembly_r",
    "window_fraction_operable",
    "window_ufactor",
    "window_shgc",
    "window_interior_shading_winter",
    "window_interior_shading_summer",
    "overhangs_front_depth",
    "overhangs_front_distance_to_top_of_window",
    "skylight_ufactor",
    "skylight_shgc",
    "door_area",
    "door_rvalue",
    "air_leakage_units",
    "air_leakage_house_pressure",
    "air_leakage_value",
    "air_leakage_type",
    "heating_system_type",
    "heating_system_fuel",
    "heating_system_heating_efficiency",
    "heating_system_fraction_heat_load_served",
    "cooling_system_type",
    "cooling_system_cooling_compressor_type",
    "heat_pump_type",
    "heat_pump_heating_efficiency_type",
    "heat_pump_heating_efficiency",
    "heat_pump_cooling_efficiency_type",
    "heat_pump_cooling_efficiency",
    "heat_pump_cooling_compressor_type",
    "heat_pump_heating_capacity_retention_fraction",
    "heat_pump_heating_capacity_retention_temp",
    "heat_pump_fraction_heat_load_served",
    "heat_pump_fraction_cool_load_served",
    "heat_pump_compressor_lockout_temp",
    "heat_pump_backup_type",
    "heat_pump_backup_fuel",
    "heat_pump_backup_heating_efficiency",
    "heat_pump_sizing_methodology",
    "heat_pump_is_ducted",
    "geothermal_loop_configuration",
    "geothermal_loop_grout_type",
    "geothermal_loop_pipe_type",
    "hvac_control_heating_weekday_setpoint",
    "hvac_control_heating_weekend_setpoint",
    "hvac_control_cooling_weekday_setpoint",
    "hvac_control_cooling_weekend_setpoint",
    "mech_vent_fan_type",
    "mech_vent_flow_rate",
    "mech_vent_hours_in_operation",
    "mech_vent_recovery_efficiency_type",
    "mech_vent_total_recovery_efficiency",
    "mech_vent_sensible_recovery_efficiency",
    "mech_vent_fan_power",
    "mech_vent_num_units_served",
    "mech_vent_2_fan_type",
    "mech_vent_2_flow_rate",
    "mech_vent_2_hours_in_operation",
    "mech_vent_2_recovery_efficiency_type",
    "mech_vent_2_total_recovery_efficiency",
    "mech_vent_2_sensible_recovery_efficiency",
    "mech_vent_2_fan_power",
    "kitchen_fans_start_hour",
    "bathroom_fans_start_hour",
    "whole_house_fan_present",
    "whole_house_fan_flow_rate",
    "whole_house_fan_power",
    "water_heater_type",
    "water_heater_fuel_type",
    "water_heater_location",
    "water_heater_tank_volume",
    "water_heater_efficiency_type",
    "water_heater_efficiency",
    "water_heater_recovery_efficiency",
    "water_heater_standby_loss",
    "water_heater_jacket_rvalue",
    "water_heater_setpoint_temperature",
    "pv_system_present",
    "pv_system_location",
    "pv_system_array_azimuth",
    "pv_system_array_tilt",
    "pv_system_max_power_output",
    "pv_system_2_present",
    "pv_system_2_array_azimuth",
    "pv_system_2_array_tilt",
    "pv_system_2_max_power_output",
    "battery_present",
    "lighting_present",
    "lighting_interior_fraction_cfl",
    "lighting_interior_fraction_lfl",
    "lighting_interior_fraction_led",
    "lighting_interior_usage_multiplier",
    "lighting_exterior_fraction_cfl",
    "lighting_exterior_fraction_lfl",
    "lighting_exterior_fraction_led",
    "lighting_garage_fraction_cfl",
    "lighting_garage_fraction_lfl",
    "lighting_garage_fraction_led",
    "dehumidifier_type",
    "dehumidifier_efficiency_type",
    "dehumidifier_efficiency",
    "dehumidifier_capacity",
    "dehumidifier_rh_setpoint",
    "dehumidifier_fraction_dehumidification_load_served",
    "clothes_washer_present",
    "clothes_washer_efficiency_type",
    "clothes_washer_efficiency",
    "clothes_washer_rated_annual_kwh",
    "clothes_washer_label_electric_rate",
    "clothes_washer_label_gas_rate",
    "clothes_washer_label_annual_gas_cost",
    "clothes_washer_label_usage",
    "clothes_washer_capacity",
    "clothes_washer_usage_multiplier",
    "clothes_dryer_present",
    "clothes_dryer_fuel_type",
    "clothes_dryer_efficiency_type",
    "clothes_dryer_efficiency",
    "clothes_dryer_usage_multiplier",
    "dishwasher_present",
    "dishwasher_efficiency_type",
    "dishwasher_efficiency",
    "dishwasher_label_electric_rate",
    "dishwasher_label_gas_rate",
    "dishwasher_label_annual_gas_cost",
    "dishwasher_label_usage",
    "dishwasher_place_setting_capacity",
    "refrigerator_present",
    "refrigerator_rated_annual_kwh",
    "extra_refrigerator_present",
    "extra_refrigerator_rated_annual_kwh",
    "extra_refrigerator_usage_multiplier",
    "freezer_present",
    "freezer_rated_annual_kwh",
    "freezer_usage_multiplier",
    "cooking_range_oven_present",
    "cooking_range_oven_fuel_type",
    "cooking_range_oven_is_induction",
    "cooking_range_oven_usage_multiplier",
    "ceiling_fan_present",
    "ceiling_fan_efficiency",
    "ceiling_fan_quantity",
    "ceiling_fan_cooling_setpoint_temp_offset",
    "misc_plug_loads_vehicle_present",
    "misc_plug_loads_vehicle_annual_kwh",
    "misc_plug_loads_vehicle_usage_multiplier",
    "pool_present",
    "pool_pump_usage_multiplier",
    "pool_heater_type",
    "pool_heater_usage_multiplier",
    "permanent_spa_present",
    "permanent_spa_pump_annual_kwh",
    "permanent_spa_heater_type",
    "permanent_spa_heater_annual_kwh",
    "geometry_overhangs_back_depth",
    "geometry_overhangs_back_distance_to_bottom_of_window",
    "geometry_overhangs_back_distance_to_top_of_window",
    "geometry_overhangs_front_depth",
    "geometry_overhangs_front_distance_to_bottom_of_window",
    "geometry_overhangs_front_distance_to_top_of_window",
    "geometry_overhangs_left_depth",
    "geometry_overhangs_left_distance_to_bottom_of_window",
    "geometry_overhangs_left_distance_to_top_of_window",
    "geometry_overhangs_right_depth",
    "geometry_overhangs_right_distance_to_bottom_of_window",
    "geometry_overhangs_right_distance_to_top_of_window",
    "heat_pump_backup_use_existing_system",
    "heat_pump_sizing_is_duct_limited",
    "misc_plug_loads_vehicle_2_usage_multiplier",
    "schedules_vacancy_period",
]

# Padded with "false" rather than a blank: pandas casts a blank Boolean to True.
BOOLEAN_COLUMNS = [
    "simulation_control_daylight_saving_enabled",
    "geometry_unit_left_wall_is_adiabatic",
    "geometry_unit_right_wall_is_adiabatic",
    "geometry_unit_front_wall_is_adiabatic",
    "geometry_unit_back_wall_is_adiabatic",
    "heat_pump_is_ducted",
    "whole_house_fan_present",
    "pv_system_present",
    "pv_system_2_present",
    "battery_present",
    "lighting_present",
    "clothes_washer_present",
    "clothes_dryer_present",
    "dishwasher_present",
    "refrigerator_present",
    "extra_refrigerator_present",
    "freezer_present",
    "cooking_range_oven_present",
    "cooking_range_oven_is_induction",
    "ceiling_fan_present",
    "misc_plug_loads_vehicle_present",
    "pool_present",
    "permanent_spa_present",
]

# The sampler-attribute block, pinned because the BN's topological
# variable order differs between networks.
ARGS_COLUMNS = [
    "Geometry Stories",
    "Geometry Building Number Units",
    "Geometry Building Horizontal Location",
    "Geometry Building Level",
    "Geometry Foundation Type",
    "Windows",
    "Insulation Wall",
    "Insulation Ceiling",
    "Insulation Foundation Wall",
    "Insulation Floor",
    "Geometry Wall Exterior Finish",
    "geometry attic type",
    "HVAC Has Shared System",
    "HVAC Heating Efficiency",
    "Spa ChaufType",
    "Usage Level",
    "Cooking Range Usage Level",
    "Clothes Washer Usage Level",
    "Clothes Dryer Usage Level",
    "Refrigerator Efficiency",
    "Refrigerator Extra Efficiency",
    "Refrigerator Usage Level",
    "Freezer Efficiency",
    "Dishwasher Energy",
    "Diswasher Usage Level",
    "Lighting Usage Level",
    "Door Area",
    "Door Rvalue",
    "Plug Load",
    "ModeConsigne",
    "Heating Setpoint",
    "Cooling Setpoint",
    "Garage Heating Setpoint",
    "Basement Heating Setpoint",
    "Mechanical Ventilation",
    "Bathroom Spot Vent Hour",
    "Natural Ventilation",
    "Range Spot Vent Hour",
    "Orientation",
    "Overhangs",
    "Vacancy Status",
    "Has PV",
    "PV Orientation",
    "PV System Size",
    "Battery",
    "Ceiling Fan",
    "Dehumidifier",
    "Insulation Roof",
    "Insulation Slab",
    "Interior Shading",
    "Radiant Barrier",
    "Roof Material",
    "Tconsignes_chauffage_H1",
    "Tconsignes_chauffage_H2",
    "Tconsignes_chauffage_H3",
    "Tconsignes_chauffage_H4",
    "Territoire_HQ",
    "Region_Administrative",
    "Type_Logement",
    "Type_Batiment",
    "Vehicule_Presence",
    "Vehicule_BornePresence",
    "ChaufEau_Presence",
    "ChaufEau_Type",
    "Spa_Presence",
    "Spa_Logement",
    "Spa_Saison",
    "Spa_Utilisation_SaisonFroide",
    "Spa_Utilisation_SaisonChaude",
    "Nombre_Etages",
    "Presence_SousSol",
    "Nombre_Pieces",
    "Nombre_Personnes",
    "LaveLinge_Type",
    "SecheLinge_Presence",
    "LaveVaisselle_Presence",
    "Congelateur_Nombre",
    "Refrigerateur_Nombre",
    "Cuisiniere_Presence",
    "Superficie_Totale",
    "Mode_Occupation",
    "Eclairage_LED",
    "An_Construction",
    "Infiltration",
    "An_ConstructionCode",
    "Source_Energie_Chauf",
    "ChaufEau_ChaufType",
    "Chauffage_Logement",
    "Climatisation",
    "Cuisiniere_Energie",
    "Presence_Garage",
    "Piscine_Presence",
    "Piscine_Type",
    "Piscine_Toile",
    "Piscine_Chauffee",
    "Piscine_ChaufType",
    "Piscine_Minuterie",
]
